version: "3.9"

services:
  bot:
    build: .
    restart: always
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:15.3
    restart: always
    env_file: ./psql/.env
    healthcheck:
      test: "bash /test-db/test.sh"
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s
    volumes:
      - "./psql/init.sh:/docker-entrypoint-initdb.d/init-user-db.sh:ro"
      - "./psql/test.sh:/test-db/test.sh:ro"
      - "./psql/data:/var/lib/postgresql/data"
