version: "3.9"

services:
  bot:
    build: .
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  postgres:
    image: postgres:15.3
    restart: always
    env_file: ./.env
    healthcheck:
      test: "pg_isready -U $APP_USER -d $APP_DB"
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s
    volumes:
      - "./psql/init.sh:/docker-entrypoint-initdb.d/init-user-db.sh:ro"
      - "./psql/data:/var/lib/postgresql/data"

  redis:
    image: redis:7.0.11
    command: "redis-server --save 60 1 --loglevel warning"
    restart: always
    healthcheck:
      test: "redis-cli ping"
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s
    volumes:
      - "./redis/data:/data"
