#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE USER $APP_USER WITH PASSWORD '$APP_PASSWORD';
	CREATE DATABASE $APP_DB;
	ALTER DATABASE $APP_DB OWNER TO $APP_USER;
EOSQL
