"""Add users_profiles

Revision ID: 29a1a74496fc
Revises: 255694b9f59d
Create Date: 2023-06-05 21:45:05.539554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29a1a74496fc'
down_revision = '255694b9f59d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'users_profiles',
        sa.Column('n', sa.INTEGER(), nullable=False),
        sa.Column('id', sa.BIGINT(), nullable=False),
        sa.Column('name', sa.VARCHAR(), nullable=False),
        sa.Column('last_name', sa.VARCHAR(), nullable=False),
        sa.Column('age', sa.INTEGER(), nullable=False),
        sa.PrimaryKeyConstraint('n'),
        sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_profiles')
    # ### end Alembic commands ###
